### ISSUE TITLE
Nothing is written to hi.txt

### ISSUE THREAD

**Issue by rarar0** [loknjinu13/week8#4]
echo $*{*MY_NAME*}* >*>* *~/*hi.txt (My edit with highlighted changes)
echo $MY_NAME >hi.txt (The original, on line 13)
echo ${MY_NAME} >> ~/hi.txt (My edit)
My recommended changes are highlighted with asterisks **
Use curly brackets for the variable name, you need an extra arrow, and use ~ to give an absolute path for hi.txt

**Comment by loknjinu13** [comment]
I followed through and it was great
