### ISSUE TITLE
Flow control

### ISSUE THREAD

**Issue by paveldanek** [loknjinu13/week8#8]
Hello!
Try to space out your screen output either by delays (command sleep x (x=seconds)) or by waiting for user input (command read (will wait for <ENTER>)). You’ll be able to see your output and any errors it throws at you. 
You could also add comments as echo commands to describe to the viewer, what you’re about to do.

Scrolling upward, I think I’ve noticed several permission problems. Once you establish flow control, you’ll notice them, too.
Good luck!
-Pavel.

**Comment by loknjinu13** [comment]
Thanks... i just followed through...
